[package]
name = "ext4tool"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]

[dependencies]
ext4 = { path = ".." }
bootsector = "0.1"
clap = "2"
error-chain = "0.11"
hexdump = "0.1"
