[package]
name = "ext4tool"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]

[dependencies]
ext4 = { path = ".." }
bootsector = "0.1"
cast = "0.2"
clap = "2"
failure = "0.1"
hexdump = "0.1"
